In [189]:
%matplotlib inline
import re
import pandas as pd
import matplotlib as plt
import numpy as np

In [190]:
master = pd.read_csv("data/Master.csv", sep=",")

In [191]:
master

,playerID,birthYear,birthMonth,birthDay,birthCountry,birthState,birthCity,deathYear,deathMonth,deathDay,...,nameLast,nameGiven,weight,height,bats,throws,debut,finalGame,retroID,bbrefID
0,aardsda01,1981.0,12.0,27.0,USA,CO,Denver,NaN,NaN,NaN,...,Aardsma,David Allan,220.0,75.0,R,R,2004-04-06,2015-08-23,aardd001,aardsda01
1,aaronha01,1934.0,2.0,5.0,USA,AL,Mobile,NaN,NaN,NaN,...,Aaron,Henry Louis,180.0,72.0,R,R,1954-04-13,1976-10-03,aaroh101,aaronha01
2,aaronto01,1939.0,8.0,5.0,USA,AL,Mobile,1984.0,8.0,16.0,...,Aaron,Tommie Lee,190.0,75.0,R,R,1962-04-10,1971-09-26,aarot101,aaronto01
3,aasedo01,1954.0,9.0,8.0,USA,CA,Orange,NaN,NaN,NaN,...,Aase,Donald William,190.0,75.0,R,R,1977-07-26,1990-10-03,aased001,aasedo01
4,abadan01,1972.0,8.0,25.0,USA,FL,Palm Beach,NaN,NaN,NaN,...,Abad,Fausto Andres,184.0,73.0,L,L,2001-09-10,2006-04-13,abada001,abadan01
5,abadfe01,1985.0,12.0,17.0,D.R.,La Romana,La Romana,NaN,NaN,NaN,...,Abad,Fernando Antonio,220.0,73.0,L,L,2010-07-28,2015-10-03,abadf001,abadfe01
6,abadijo01,1854.0,11.0,4.0,USA,PA,Philadelphia,1905.0,5.0,17.0,...,Abadie,John W.,192.0,72.0,R,R,1875-04-26,1875-06-10,abadj101,abadijo01
7,abbated01,1877.0,4.0,15.0,USA,PA,Latrobe,1957.0,1.0,6.0,...,Abbaticchio,Edward James,170.0,71.0,R,R,1897-09-04,1910-09-15,abbae101,abbated01
8,abbeybe01,1869.0,11.0,11.0,USA,VT,Essex,1962.0,6.0,11.0,...,Abbey,Bert Wood,175.0,71.0,R,R,1892-06-14,1896-09-23,abbeb101,abbeybe01
9,abbeych01,1866.0,10.0,14.0,USA,NE,Falls City,1926.0,4.0,27.0,...,Abbey,Charles S.,169.0,68.0,L,L,1893-08-16,1897-08-19,abbec101,abbeych01
10,abbotda01,1862.0,3.0,16.0,USA,OH,Portage,1930.0,2.0,13.0,...,Abbott,Leander Franklin,190.0,71.0,R,R,1890-04-19,1890-05-23,abbod101,abbotda01
11,abbotfr01,1874.0,10.0,22.0,USA,OH,Versailles,1935.0,6.0,11.0,...,Abbott,Harry Frederick,180.0,70.0,R,R,1903-04-25,1905-09-20,abbof101,abbotfr01
12,abbotgl01,1951.0,2.0,16.0,USA,AR,Little Rock,NaN,NaN,NaN,...,Abbott,William Glenn,200.0,78.0,R,R,1973-07-29,1984-08-08,abbog001,abbotgl01
13,abbotje01,1972.0,8.0,17.0,USA,GA,Atlanta,NaN,NaN,NaN,...,Abbott,Jeffrey William,190.0,74.0,R,L,1997-06-10,2001-09-29,abboj002,abbotje01
14,abbotji01,1967.0,9.0,19.0,USA,MI,Flint,NaN,NaN,NaN,...,Abbott,James Anthony,200.0,75.0,L,L,1989-04-08,1999-07-21,abboj001,abbotji01
15,abbotku01,1969.0,6.0,2.0,USA,OH,Zanesville,NaN,NaN,NaN,...,Abbott,Kurt Thomas,180.0,71.0,R,R,1993-09-07,2001-04-13,abbok002,abbotku01
16,abbotky01,1968.0,2.0,18.0,USA,MA,Newburyport,NaN,NaN,NaN,...,Abbott,Lawrence Kyle,200.0,76.0,L,L,1991-09-10,1996-08-24,abbok001,abbotky01
17,abbotod01,1888.0,9.0,5.0,USA,PA,New Eagle,1933.0,4.0,13.0,...,Abbott,Ody Cleon,180.0,74.0,R,R,1910-09-10,1910-10-15,abboo101,abbotod01
18,abbotpa01,1967.0,9.0,15.0,USA,CA,Van Nuys,NaN,NaN,NaN,...,Abbott,Paul David,185.0,75.0,R,R,1990-08-21,2004-08-07,abbop001,abbotpa01
19,aberal01,1927.0,7.0,31.0,USA,OH,Cleveland,1993.0,5.0,20.0,...,Aber,Albert Julius,195.0,74.0,L,L,1950-09-15,1957-09-11,abera101,aberal01
20,abercda01,1850.0,1.0,2.0,USA,OK,Fort Towson,1939.0,11.0,11.0,...,Abercrombie,Francis Patterson,NaN,NaN,NaN,NaN,1871-10-21,1871-10-21,aberd101,abercda01
21,abercre01,1980.0,7.0,15.0,USA,GA,Columbus,NaN,NaN,NaN,...,Abercrombie,Reginald Damascus,215.0,75.0,R,R,2006-04-04,2008-09-28,aberr001,abercre01
22,abernbi01,1929.0,1.0,30.0,USA,CA,Torrance,2006.0,2.0,19.0,...,Abernathie,William Edward,190.0,70.0,R,R,1952-09-27,1952-09-27,aberb101,abernbi01
23,abernbr01,1977.0,9.0,23.0,USA,GA,Atlanta,NaN,NaN,NaN,...,Abernathy,Michael Brent,185.0,73.0,R,R,2001-06-25,2005-09-29,aberb001,abernbr01
24,abernte01,1921.0,10.0,30.0,USA,NC,Bynum,2001.0,11.0,16.0,...,Abernathy,Talmadge Lafayette,210.0,74.0,R,L,1942-09-19,1944-04-29,abert102,abernte01
25,abernte02,1933.0,3.0,6.0,USA,NC,Stanley,2004.0,12.0,16.0,...,Abernathy,Theodore Wade,215.0,76.0,R,R,1955-04-13,1972-09-30,abert101,abernte02
26,abernwo01,1915.0,2.0,1.0,USA,NC,Forest City,1994.0,12.0,5.0,...,Abernathy,Virgil Woodrow,170.0,72.0,L,L,1946-07-28,1947-04-17,aberw101,abernwo01
27,aberscl01,1921.0,8.0,28.0,USA,IL,Chicago,1973.0,6.0,23.0,...,Aberson,Clifford Alexander,200.0,72.0,R,R,1947-07-18,1949-05-09,aberc101,aberscl01
28,ablesha01,1883.0,10.0,4.0,USA,TX,Terrell,1951.0,2.0,8.0,...,Ables,Harry Terrell,200.0,74.0,R,L,1905-09-04,1911-05-05,ableh101,ablesha01
29,abnersh01,1966.0,6.0,17.0,USA,OH,Hamilton,NaN,NaN,NaN,...,Abner,Shawn Wesley,190.0,73.0,R,R,1987-09-08,1992-10-03,abnes001,abnersh01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18816,zimmejo02,1986.0,5.0,23.0,USA,WI,Auburndale,NaN,NaN,NaN,...,Zimmermann,Jordan M.,225.0,74.0,R,R,2009-04-20,2015-09-30,zimmj003,zimmejo02
18817,zimmero01,1916.0,9.0,13.0,USA,PA,Pine Grove,1991.0,11.0,22.0,...,Zimmerman,Roy Franklin,187.0,74.0,L,L,1945-08-27,1945-09-30,zimmr101,zimmero01
18818,zimmery01,1984.0,9.0,28.0,USA,NC,Washington,NaN,NaN,NaN,...,Zimmerman,Ryan Wallace,220.0,75.0,R,R,2005-09-01,2015-09-07,zimmr001,zimmery01
18819,zinkch01,1979.0,8.0,26.0,USA,CA,Carmichael,NaN,NaN,NaN,...,Zink,Charles Tadao,190.0,73.0,R,R,2008-08-12,2008-08-12,zinkc001,zinkch01
18820,zinkwa01,1898.0,11.0,21.0,USA,MA,Pittsfield,1964.0,6.0,12.0,...,Zink,Walter Noble,165.0,72.0,R,R,1921-07-06,1921-07-19,zinkw101,zinkwa01
18821,zinnfr01,1865.0,12.0,21.0,USA,PA,Phoenixville,1936.0,5.0,12.0,...,Zinn,Frank Patrick,150.0,68.0,NaN,NaN,1888-04-18,1888-05-03,zinnf101,zinnfr01
18822,zinngu01,1887.0,2.0,13.0,USA,WV,Holbrook,1949.0,10.0,6.0,...,Zinn,Guy,170.0,70.0,L,R,1911-09-11,1915-09-16,zinng101,zinngu01
18823,zinnji01,1895.0,1.0,21.0,USA,AR,Benton,1991.0,2.0,26.0,...,Zinn,James Edward,195.0,72.0,L,R,1919-09-04,1929-08-25,zinnj101,zinnji01
18824,zinsebi01,1918.0,1.0,6.0,USA,NY,Astoria,1993.0,2.0,16.0,...,Zinser,William Francis,185.0,73.0,R,R,1944-08-19,1944-08-26,zinsb101,zinsebi01
18825,zinteal01,1968.0,5.0,19.0,USA,TX,El Paso,NaN,NaN,NaN,...,Zinter,Alan Michael,200.0,74.0,B,R,2002-06-18,2004-10-03,zinta001,zinteal01
18826,zipfebu01,1938.0,11.0,18.0,USA,IL,Belleville,NaN,NaN,NaN,...,Zipfel,Marion Sylvester,200.0,75.0,L,R,1961-07-26,1962-09-30,zipfb101,zipfebu01
18827,ziskri01,1949.0,2.0,6.0,USA,NY,Brooklyn,NaN,NaN,NaN,...,Zisk,Richard Walter,200.0,73.0,R,R,1971-09-08,1983-09-21,ziskr101,ziskri01
18828,zitoba01,1978.0,5.0,13.0,USA,NV,Las Vegas,NaN,NaN,NaN,...,Zito,Barry William,205.0,74.0,L,L,2000-07-22,2015-09-30,zitob001,zitoba01
18829,zitzmbi01,1895.0,11.0,19.0,USA,NY,Long Island City,1985.0,5.0,29.0,...,Zitzmann,William Arthur,175.0,70.0,R,R,1919-04-27,1929-09-25,zitzb101,zitzmbi01
18830,zmiched01,1884.0,10.0,1.0,USA,OH,Cleveland,1950.0,8.0,20.0,...,Zmich,Edward Albert,180.0,72.0,L,L,1910-07-23,1911-06-01,zmice101,zmiched01
18831,zobribe01,1981.0,5.0,26.0,USA,IL,Eureka,NaN,NaN,NaN,...,Zobrist,Benjamin Thomas,210.0,75.0,B,R,2006-08-01,2015-10-04,zobrb001,zobribe01
18832,zoccope01,1977.0,2.0,6.0,USA,NY,Bronx,NaN,NaN,NaN,...,Zoccolillo,Peter Jude,200.0,74.0,L,R,2003-09-05,2003-09-28,zoccp001,zoccope01
18833,zoldasa01,1918.0,12.0,8.0,USA,NY,Brooklyn,1966.0,8.0,25.0,...,Zoldak,Samuel Walter,185.0,71.0,L,L,1944-05-13,1952-08-26,zolds101,zoldasa01
18834,zoskyed01,1968.0,2.0,10.0,USA,CA,Whittier,NaN,NaN,NaN,...,Zosky,Edward James,175.0,72.0,R,R,1991-09-02,2000-10-01,zoske001,zoskyed01
18835,zuberbi01,1913.0,3.0,26.0,USA,IA,Middle Amana,1982.0,11.0,2.0,...,Zuber,William Henry,195.0,74.0,R,R,1936-09-16,1947-09-23,zubeb101,zuberbi01
18836,zuberjo01,1969.0,12.0,10.0,USA,CA,Encino,NaN,NaN,NaN,...,Zuber,Jon Edward,190.0,73.0,L,L,1996-04-19,1998-09-27,zubej001,zuberjo01
18837,zuletju01,1975.0,3.0,28.0,Panama,Panama,Panama,NaN,NaN,NaN,...,Zuleta,Julio Ernesto,230.0,78.0,R,R,2000-04-06,2001-06-25,zulej001,zuletju01
18838,zumayjo01,1984.0,11.0,9.0,USA,CA,Chula Vista,NaN,NaN,NaN,...,Zumaya,Joel Martin,215.0,75.0,R,R,2006-04-03,2010-06-28,zumaj001,zumayjo01
18839,zuninmi01,1991.0,3.0,25.0,USA,FL,Cape Coral,NaN,NaN,NaN,...,Zunino,Michael Accorsi,220.0,74.0,R,R,2013-06-12,2015-08-27,zunim001,zuninmi01
18840,zupcibo01,1966.0,8.0,18.0,USA,PA,Pittsburgh,NaN,NaN,NaN,...,Zupcic,Robert,220.0,76.0,R,R,1991-09-07,1994-08-04,zupcb001,zupcibo01
18841,zupofr01,1939.0,8.0,29.0,USA,CA,San Francisco,2005.0,3.0,25.0,...,Zupo,Frank Joseph,182.0,71.0,L,R,1957-07-01,1961-05-09,zupof101,zupofr01
18842,zuvelpa01,1958.0,10.0,31.0,USA,CA,San Mateo,NaN,NaN,NaN,...,Zuvella,Paul,173.0,72.0,R,R,1982-09-04,1991-05-02,zuvep001,zuvelpa01
18843,zuverge01,1924.0,8.0,20.0,USA,MI,Holland,2014.0,9.0,8.0,...,Zuverink,George,195.0,76.0,R,R,1951-04-21,1959-06-15,zuveg101,zuverge01
18844,zwilldu01,1888.0,11.0,2.0,USA,MO,St. Louis,1978.0,3.0,27.0,...,Zwilling,Edward Harrison,160.0,66.0,L,L,1910-08-14,1916-07-12,zwild101,zwilldu01
18845,zychto01,1990.0,8.0,7.0,USA,IL,Monee,NaN,NaN,NaN,...,Zych,Anthony Aaron,190.0,75.0,R,R,2015-09-04,2015-10-03,zycht001,zychto01

In [192]:
master = master[["playerID", "nameFirst", "nameLast", "finalGame"]]

In [193]:
master.index = master["playerID"]

In [194]:
master = master[["nameFirst", "nameLast", "finalGame"]]

In [195]:
len(master)

18846

In [226]:
master.head()

          nameFirst nameLast   finalGame
playerID
aardsda01     David  Aardsma  2015-08-23
aaronha01      Hank    Aaron  1976-10-03
aaronto01    Tommie    Aaron  1971-09-26
aasedo01        Don     Aase  1990-10-03
abadan01       Andy     Abad  2006-04-13

In [237]:
living_master = master[master.finalGame != master.finalGame.isnull()]

In [238]:
living_master.head()

          nameFirst nameLast   finalGame
playerID
aardsda01     David  Aardsma  2015-08-23
aaronha01      Hank    Aaron  1976-10-03
aaronto01    Tommie    Aaron  1971-09-26
aasedo01        Don     Aase  1990-10-03
abadan01       Andy     Abad  2006-04-13

In [215]:
batting = pd.read_csv("data/Batting.csv", sep=",")

In [216]:
batting = batting[["playerID", "H", "BB", "HBP", "AB", "SF"]]

In [217]:
batting.index = batting.pop('playerID')

In [218]:
batting.head()

              H   BB  HBP     AB  SF
playerID
abercda01   0.0  0.0  NaN    4.0 NaN
addybo01   32.0  4.0  NaN  118.0 NaN
allisar01  40.0  2.0  NaN  137.0 NaN
allisdo01  44.0  0.0  NaN  133.0 NaN
ansonca01  39.0  2.0  NaN  120.0 NaN

In [219]:
batting

               H    BB   HBP     AB    SF
playerID
abercda01    0.0   0.0   NaN    4.0   NaN
addybo01    32.0   4.0   NaN  118.0   NaN
allisar01   40.0   2.0   NaN  137.0   NaN
allisdo01   44.0   0.0   NaN  133.0   NaN
ansonca01   39.0   2.0   NaN  120.0   NaN
armstbo01   11.0   0.0   NaN   49.0   NaN
barkeal01    1.0   1.0   NaN    4.0   NaN
barnero01   63.0  13.0   NaN  157.0   NaN
barrebi01    1.0   0.0   NaN    5.0   NaN
barrofr01   13.0   0.0   NaN   86.0   NaN
bassjo01    27.0   3.0   NaN   89.0   NaN
battijo01    0.0   1.0   NaN    3.0   NaN
bealsto01    7.0   2.0   NaN   36.0   NaN
beaveed01    6.0   0.0   NaN   15.0   NaN
bechtge01   33.0   2.0   NaN   94.0   NaN
bellast01   32.0   9.0   NaN  128.0   NaN
berkena01    0.0   0.0   NaN    4.0   NaN
berryto01    1.0   0.0   NaN    4.0   NaN
berthha01   17.0   4.0   NaN   73.0   NaN
biermch01    0.0   1.0   NaN    2.0   NaN
birdge01    28.0   3.0   NaN  106.0   NaN
birdsda01   46.0   4.0   NaN  152.0   NaN
brainas01   30.0   7.0   NaN  134.0   NaN
brannmi01    1.0   0.0   NaN   14.0   NaN
burrohe01   15.0   1.0   NaN   63.0   NaN
careyto01   20.0   2.0   NaN   87.0   NaN
carleji01   32.0   8.0   NaN  127.0   NaN
conefr01    20.0   8.0   NaN   77.0   NaN
connone01    7.0   0.0   NaN   33.0   NaN
cravebi01   38.0   3.0   NaN  118.0   NaN
...          ...   ...   ...    ...   ...
wislema01    4.0   2.0   0.0   29.0   0.0
wojcias01    0.0   0.0   0.0    0.0   0.0
wolfra02     0.0   0.0   0.0    0.0   0.0
wongko01   146.0  36.0  15.0  557.0   5.0
woodal02     5.0   3.0   0.0   33.0   0.0
woodal02     4.0   1.0   0.0   22.0   0.0
woodtr01     3.0   2.0   0.0   30.0   0.0
wootero01    0.0   0.0   0.0    1.0   0.0
worleva01    3.0   0.0   0.0   17.0   0.0
wrighda03   44.0  22.0   0.0  152.0   0.0
wrighmi01    1.0   0.0   0.0    2.0   0.0
wrighst01    0.0   0.0   0.0    1.0   0.0
wrighwe01    0.0   0.0   0.0    0.0   0.0
wrighwe01    0.0   0.0   0.0    0.0   0.0
yateski01    0.0   0.0   0.0    0.0   0.0
yelicch01  143.0  47.0   2.0  476.0   0.0
ynoara01    33.0   3.0   0.0  127.0   0.0
youngch03    2.0   0.0   0.0    4.0   0.0
youngch04   80.0  30.0   3.0  318.0   2.0
youngde03   47.0   4.0   1.0  174.0   1.0
younger03   13.0   6.0   0.0   77.0   0.0
younger03    0.0   0.0   1.0    8.0   0.0
zieglbr01    0.0   0.0   0.0    0.0   0.0
zimmejo02   10.0   0.0   0.0   63.0   0.0
zimmery01   86.0  33.0   1.0  346.0  10.0
zitoba01     0.0   0.0   0.0    0.0   0.0
zobribe01   63.0  33.0   0.0  235.0   3.0
zobribe01   66.0  29.0   1.0  232.0   2.0
zuninmi01   61.0  21.0   5.0  350.0   2.0
zychto01     0.0   0.0   0.0    0.0   0.0

[101332 rows x 5 columns]

In [204]:
salaries = pd.read_csv("data/Salaries.csv", sep=",")

In [205]:
salaries = salaries[["salary", "playerID"]]

In [206]:
salaries.index = salaries.pop("playerID")

In [207]:
salaries.head()

           salary
playerID
barkele01  870000
bedrost01  550000
benedbr01  545000
campri01   633333
ceronri01  625000

In [221]:
master_and_batting = pd.merge(batting, master, on=batting.index)

KeyError: "Index(['abercda01', 'addybo01', 'allisar01', 'allisdo01', 'ansonca01',\n       'armstbo01', 'barkeal01', 'barnero01', 'barrebi01', 'barrofr01',\n       ...\n       'younger03', 'younger03', 'zieglbr01', 'zimmejo02', 'zimmery01',\n       'zitoba01', 'zobribe01', 'zobribe01', 'zuninmi01', 'zychto01'],\n      dtype='object', name='playerID', length=101332) not in index"

ValueError: Shape of passed values is (8, 101519), indices imply (8, 18846)

In [213]:
master_and_batting

              AB    BB     H  HBP  SF   finalGame nameFirst    nameLast
playerID
abercda01    4.0   0.0   0.0  NaN NaN         NaN       NaN         NaN
addybo01   118.0   4.0  32.0  NaN NaN         NaN       NaN         NaN
allisar01  137.0   2.0  40.0  NaN NaN         NaN       NaN         NaN
allisdo01  133.0   0.0  44.0  NaN NaN         NaN       NaN         NaN
ansonca01  120.0   2.0  39.0  NaN NaN         NaN       NaN         NaN
armstbo01   49.0   0.0  11.0  NaN NaN         NaN       NaN         NaN
barkeal01    4.0   1.0   1.0  NaN NaN         NaN       NaN         NaN
barnero01  157.0  13.0  63.0  NaN NaN         NaN       NaN         NaN
barrebi01    5.0   0.0   1.0  NaN NaN         NaN       NaN         NaN
barrofr01   86.0   0.0  13.0  NaN NaN         NaN       NaN         NaN
bassjo01    89.0   3.0  27.0  NaN NaN         NaN       NaN         NaN
battijo01    3.0   1.0   0.0  NaN NaN         NaN       NaN         NaN
bealsto01   36.0   2.0   7.0  NaN NaN         NaN       NaN         NaN
beaveed01   15.0   0.0   6.0  NaN NaN         NaN       NaN         NaN
bechtge01   94.0   2.0  33.0  NaN NaN         NaN       NaN         NaN
bellast01  128.0   9.0  32.0  NaN NaN         NaN       NaN         NaN
berkena01    4.0   0.0   0.0  NaN NaN         NaN       NaN         NaN
berryto01    4.0   0.0   1.0  NaN NaN         NaN       NaN         NaN
berthha01   73.0   4.0  17.0  NaN NaN         NaN       NaN         NaN
biermch01    2.0   1.0   0.0  NaN NaN         NaN       NaN         NaN
birdge01   106.0   3.0  28.0  NaN NaN         NaN       NaN         NaN
birdsda01  152.0   4.0  46.0  NaN NaN         NaN       NaN         NaN
brainas01  134.0   7.0  30.0  NaN NaN         NaN       NaN         NaN
brannmi01   14.0   0.0   1.0  NaN NaN         NaN       NaN         NaN
burrohe01   63.0   1.0  15.0  NaN NaN         NaN       NaN         NaN
careyto01   87.0   2.0  20.0  NaN NaN         NaN       NaN         NaN
carleji01  127.0   8.0  32.0  NaN NaN         NaN       NaN         NaN
conefr01    77.0   8.0  20.0  NaN NaN         NaN       NaN         NaN
connone01   33.0   0.0   7.0  NaN NaN         NaN       NaN         NaN
cravebi01  118.0   3.0  38.0  NaN NaN         NaN       NaN         NaN
...          ...   ...   ...  ...  ..         ...       ...         ...
zimmejo02    NaN   NaN   NaN  NaN NaN  2015-09-30    Jordan  Zimmermann
zimmero01    NaN   NaN   NaN  NaN NaN  1945-09-30       Roy   Zimmerman
zimmery01    NaN   NaN   NaN  NaN NaN  2015-09-07      Ryan   Zimmerman
zinkch01     NaN   NaN   NaN  NaN NaN  2008-08-12   Charlie        Zink
zinkwa01     NaN   NaN   NaN  NaN NaN  1921-07-19    Walter        Zink
zinnfr01     NaN   NaN   NaN  NaN NaN  1888-05-03     Frank        Zinn
zinngu01     NaN   NaN   NaN  NaN NaN  1915-09-16       Guy        Zinn
zinnji01     NaN   NaN   NaN  NaN NaN  1929-08-25     Jimmy        Zinn
zinsebi01    NaN   NaN   NaN  NaN NaN  1944-08-26      Bill      Zinser
zinteal01    NaN   NaN   NaN  NaN NaN  2004-10-03      Alan      Zinter
zipfebu01    NaN   NaN   NaN  NaN NaN  1962-09-30       Bud      Zipfel
ziskri01     NaN   NaN   NaN  NaN NaN  1983-09-21    Richie        Zisk
zitoba01     NaN   NaN   NaN  NaN NaN  2015-09-30     Barry        Zito
zitzmbi01    NaN   NaN   NaN  NaN NaN  1929-09-25     Billy    Zitzmann
zmiched01    NaN   NaN   NaN  NaN NaN  1911-06-01        Ed       Zmich
zobribe01    NaN   NaN   NaN  NaN NaN  2015-10-04       Ben     Zobrist
zoccope01    NaN   NaN   NaN  NaN NaN  2003-09-28     Peter  Zoccolillo
zoldasa01    NaN   NaN   NaN  NaN NaN  1952-08-26       Sam      Zoldak
zoskyed01    NaN   NaN   NaN  NaN NaN  2000-10-01     Eddie       Zosky
zuberbi01    NaN   NaN   NaN  NaN NaN  1947-09-23      Bill       Zuber
zuberjo01    NaN   NaN   NaN  NaN NaN  1998-09-27       Jon       Zuber
zuletju01    NaN   NaN   NaN  NaN NaN  2001-06-25     Julio      Zuleta
zumayjo01    NaN   NaN   NaN  NaN NaN  2010-06-28      Joel      Zumaya
zuninmi01    NaN   NaN   NaN  NaN NaN  2015-08-27      Mike      Zunino
zupcibo01    NaN   NaN   NaN  NaN NaN  1994-08-04       Bob      Zupcic
zupofr01     NaN   NaN   NaN  NaN NaN  1961-05-09     Frank        Zupo
zuvelpa01    NaN   NaN   NaN  NaN NaN  1991-05-02      Paul     Zuvella
zuverge01    NaN   NaN   NaN  NaN NaN  1959-06-15    George    Zuverink
zwilldu01    NaN   NaN   NaN  NaN NaN  1916-07-12     Dutch    Zwilling
zychto01     NaN   NaN   NaN  NaN NaN  2015-10-03      Tony        Zych

[120178 rows x 8 columns]

In [ ]:
def get_obp(H, AB, BB, SF, HBP=0):
    if HBP.isna:
        HBP=0
    return (H+BB+HBP/AB+BB+HBP+SF)

In [ ]:
batting['OBP'] = get_obp(batting['H'], batting['AB'], batting['BB'], batting['SF'], batting['HBP'])